In [1]:
import pandas as pd

df = pd.read_csv("events.csv")
df.head()

,event_id,user_id,event_name,event_description,event_type,location,event_image,start_date,end_date,created_at,updated_at
0,1,646,Persona Fest,A 24-hour coding hackathon solving real-world ...,cultural,Delhi,img3.png,2023-09-05 01:55:33,2023-09-06 01:55:33,2023-08-31 01:55:33,2023-09-20 01:55:33
1,2,582,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",placement,Delhi,img3.png,2023-08-31 11:46:03,2023-08-31 11:46:03,2023-08-30 11:46:03,2023-09-06 11:46:03
2,3,487,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Bangalore,img3.png,2024-07-20 10:45:21,2024-07-23 10:45:21,2024-07-15 10:45:21,2024-07-19 10:45:21
3,4,623,Aarohan,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Chennai,img2.png,2023-08-07 17:01:39,2023-08-09 17:01:39,2023-08-01 17:01:39,2023-08-31 17:01:39
4,5,118,MindSpark,The primary mission of the fest is to provide ...,hackathon,Mumbai,img1.png,2024-08-11 02:09:06,2024-08-14 02:09:06,2024-08-07 02:09:06,2024-08-19 02:09:06

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   event_id           2500 non-null   int64
 1   user_id            2500 non-null   int64
 2   event_name         2500 non-null   str
 3   event_description  2500 non-null   str
 4   event_type         2500 non-null   str
 5   location           2500 non-null   str
 6   event_image        2500 non-null   str
 7   start_date         2500 non-null   str
 8   end_date           2500 non-null   str
 9   created_at         2500 non-null   str
 10  updated_at         2500 non-null   str
dtypes: int64(2), str(9)
memory usage: 215.0 KB

In [3]:

df.isnull().sum()

event_id             0
user_id              0
event_name           0
event_description    0
event_type           0
location             0
event_image          0
start_date           0
end_date             0
created_at           0
updated_at           0
dtype: int64

In [4]:
df = df.drop_duplicates()

In [5]:
df

,event_id,user_id,event_name,event_description,event_type,location,event_image,start_date,end_date,created_at,updated_at
0,1,646,Persona Fest,A 24-hour coding hackathon solving real-world ...,cultural,Delhi,img3.png,2023-09-05 01:55:33,2023-09-06 01:55:33,2023-08-31 01:55:33,2023-09-20 01:55:33
1,2,582,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",placement,Delhi,img3.png,2023-08-31 11:46:03,2023-08-31 11:46:03,2023-08-30 11:46:03,2023-09-06 11:46:03
2,3,487,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Bangalore,img3.png,2024-07-20 10:45:21,2024-07-23 10:45:21,2024-07-15 10:45:21,2024-07-19 10:45:21
3,4,623,Aarohan,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Chennai,img2.png,2023-08-07 17:01:39,2023-08-09 17:01:39,2023-08-01 17:01:39,2023-08-31 17:01:39
4,5,118,MindSpark,The primary mission of the fest is to provide ...,hackathon,Mumbai,img1.png,2024-08-11 02:09:06,2024-08-14 02:09:06,2024-08-07 02:09:06,2024-08-19 02:09:06
...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,643,Hack-o-heist 2025,A 24-hour coding hackathon solving real-world ...,placement,Mumbai,img4.png,2024-10-13 23:40:56,2024-10-15 23:40:56,2024-10-12 23:40:56,2024-10-18 23:40:56
2496,2497,84,MindSpark,"Aarohan is divided into cultural, technical, m...",placement,Chennai,img3.png,2025-06-22 00:22:54,2025-06-22 00:22:54,2025-06-20 00:22:54,2025-07-20 00:22:54
2497,2498,109,Hack-o-heist 2025,The primary mission of the fest is to provide ...,technical,Delhi,img3.png,2023-08-30 12:26:52,2023-09-01 12:26:52,2023-08-27 12:26:52,2023-09-12 12:26:52
2498,2499,17,Campus Placement Drive,Campus placement drive with multiple recruiters.,hackathon,Mumbai,img4.png,2024-07-16 01:52:21,2024-07-16 01:52:21,2024-07-15 01:52:21,2024-07-30 01:52:21
2499,2500,830,MindSpark,Campus placement drive with multiple recruiters.,festival,Delhi,img3.png,2024-01-13 08:11:37,2024-01-15 08:11:37,2024-01-11 08:11:37,2024-01-20 08:11:37

In [6]:
df = df.drop_duplicates(subset=['event_id'])

In [7]:
df

,event_id,user_id,event_name,event_description,event_type,location,event_image,start_date,end_date,created_at,updated_at
0,1,646,Persona Fest,A 24-hour coding hackathon solving real-world ...,cultural,Delhi,img3.png,2023-09-05 01:55:33,2023-09-06 01:55:33,2023-08-31 01:55:33,2023-09-20 01:55:33
1,2,582,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",placement,Delhi,img3.png,2023-08-31 11:46:03,2023-08-31 11:46:03,2023-08-30 11:46:03,2023-09-06 11:46:03
2,3,487,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Bangalore,img3.png,2024-07-20 10:45:21,2024-07-23 10:45:21,2024-07-15 10:45:21,2024-07-19 10:45:21
3,4,623,Aarohan,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Chennai,img2.png,2023-08-07 17:01:39,2023-08-09 17:01:39,2023-08-01 17:01:39,2023-08-31 17:01:39
4,5,118,MindSpark,The primary mission of the fest is to provide ...,hackathon,Mumbai,img1.png,2024-08-11 02:09:06,2024-08-14 02:09:06,2024-08-07 02:09:06,2024-08-19 02:09:06
...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,643,Hack-o-heist 2025,A 24-hour coding hackathon solving real-world ...,placement,Mumbai,img4.png,2024-10-13 23:40:56,2024-10-15 23:40:56,2024-10-12 23:40:56,2024-10-18 23:40:56
2496,2497,84,MindSpark,"Aarohan is divided into cultural, technical, m...",placement,Chennai,img3.png,2025-06-22 00:22:54,2025-06-22 00:22:54,2025-06-20 00:22:54,2025-07-20 00:22:54
2497,2498,109,Hack-o-heist 2025,The primary mission of the fest is to provide ...,technical,Delhi,img3.png,2023-08-30 12:26:52,2023-09-01 12:26:52,2023-08-27 12:26:52,2023-09-12 12:26:52
2498,2499,17,Campus Placement Drive,Campus placement drive with multiple recruiters.,hackathon,Mumbai,img4.png,2024-07-16 01:52:21,2024-07-16 01:52:21,2024-07-15 01:52:21,2024-07-30 01:52:21
2499,2500,830,MindSpark,Campus placement drive with multiple recruiters.,festival,Delhi,img3.png,2024-01-13 08:11:37,2024-01-15 08:11:37,2024-01-11 08:11:37,2024-01-20 08:11:37

In [8]:
#Remove rows with missing important columns
df = df.dropna(subset=['event_id', 'user_id', 'created_at'])

In [9]:
df

,event_id,user_id,event_name,event_description,event_type,location,event_image,start_date,end_date,created_at,updated_at
0,1,646,Persona Fest,A 24-hour coding hackathon solving real-world ...,cultural,Delhi,img3.png,2023-09-05 01:55:33,2023-09-06 01:55:33,2023-08-31 01:55:33,2023-09-20 01:55:33
1,2,582,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",placement,Delhi,img3.png,2023-08-31 11:46:03,2023-08-31 11:46:03,2023-08-30 11:46:03,2023-09-06 11:46:03
2,3,487,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Bangalore,img3.png,2024-07-20 10:45:21,2024-07-23 10:45:21,2024-07-15 10:45:21,2024-07-19 10:45:21
3,4,623,Aarohan,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Chennai,img2.png,2023-08-07 17:01:39,2023-08-09 17:01:39,2023-08-01 17:01:39,2023-08-31 17:01:39
4,5,118,MindSpark,The primary mission of the fest is to provide ...,hackathon,Mumbai,img1.png,2024-08-11 02:09:06,2024-08-14 02:09:06,2024-08-07 02:09:06,2024-08-19 02:09:06
...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,643,Hack-o-heist 2025,A 24-hour coding hackathon solving real-world ...,placement,Mumbai,img4.png,2024-10-13 23:40:56,2024-10-15 23:40:56,2024-10-12 23:40:56,2024-10-18 23:40:56
2496,2497,84,MindSpark,"Aarohan is divided into cultural, technical, m...",placement,Chennai,img3.png,2025-06-22 00:22:54,2025-06-22 00:22:54,2025-06-20 00:22:54,2025-07-20 00:22:54
2497,2498,109,Hack-o-heist 2025,The primary mission of the fest is to provide ...,technical,Delhi,img3.png,2023-08-30 12:26:52,2023-09-01 12:26:52,2023-08-27 12:26:52,2023-09-12 12:26:52
2498,2499,17,Campus Placement Drive,Campus placement drive with multiple recruiters.,hackathon,Mumbai,img4.png,2024-07-16 01:52:21,2024-07-16 01:52:21,2024-07-15 01:52:21,2024-07-30 01:52:21
2499,2500,830,MindSpark,Campus placement drive with multiple recruiters.,festival,Delhi,img3.png,2024-01-13 08:11:37,2024-01-15 08:11:37,2024-01-11 08:11:37,2024-01-20 08:11:37

In [10]:

date_cols = ['start_date', 'end_date', 'created_at', 'updated_at']

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

In [11]:
df[col]

0      2023-09-20 01:55:33
1      2023-09-06 11:46:03
2      2024-07-19 10:45:21
3      2023-08-31 17:01:39
4      2024-08-19 02:09:06
               ...
2495   2024-10-18 23:40:56
2496   2025-07-20 00:22:54
2497   2023-09-12 12:26:52
2498   2024-07-30 01:52:21
2499   2024-01-20 08:11:37
Name: updated_at, Length: 2500, dtype: datetime64[us]

In [12]:
df = df.dropna(subset=['created_at'])

In [13]:
df

,event_id,user_id,event_name,event_description,event_type,location,event_image,start_date,end_date,created_at,updated_at
0,1,646,Persona Fest,A 24-hour coding hackathon solving real-world ...,cultural,Delhi,img3.png,2023-09-05 01:55:33,2023-09-06 01:55:33,2023-08-31 01:55:33,2023-09-20 01:55:33
1,2,582,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",placement,Delhi,img3.png,2023-08-31 11:46:03,2023-08-31 11:46:03,2023-08-30 11:46:03,2023-09-06 11:46:03
2,3,487,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Bangalore,img3.png,2024-07-20 10:45:21,2024-07-23 10:45:21,2024-07-15 10:45:21,2024-07-19 10:45:21
3,4,623,Aarohan,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Chennai,img2.png,2023-08-07 17:01:39,2023-08-09 17:01:39,2023-08-01 17:01:39,2023-08-31 17:01:39
4,5,118,MindSpark,The primary mission of the fest is to provide ...,hackathon,Mumbai,img1.png,2024-08-11 02:09:06,2024-08-14 02:09:06,2024-08-07 02:09:06,2024-08-19 02:09:06
...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,643,Hack-o-heist 2025,A 24-hour coding hackathon solving real-world ...,placement,Mumbai,img4.png,2024-10-13 23:40:56,2024-10-15 23:40:56,2024-10-12 23:40:56,2024-10-18 23:40:56
2496,2497,84,MindSpark,"Aarohan is divided into cultural, technical, m...",placement,Chennai,img3.png,2025-06-22 00:22:54,2025-06-22 00:22:54,2025-06-20 00:22:54,2025-07-20 00:22:54
2497,2498,109,Hack-o-heist 2025,The primary mission of the fest is to provide ...,technical,Delhi,img3.png,2023-08-30 12:26:52,2023-09-01 12:26:52,2023-08-27 12:26:52,2023-09-12 12:26:52
2498,2499,17,Campus Placement Drive,Campus placement drive with multiple recruiters.,hackathon,Mumbai,img4.png,2024-07-16 01:52:21,2024-07-16 01:52:21,2024-07-15 01:52:21,2024-07-30 01:52:21
2499,2500,830,MindSpark,Campus placement drive with multiple recruiters.,festival,Delhi,img3.png,2024-01-13 08:11:37,2024-01-15 08:11:37,2024-01-11 08:11:37,2024-01-20 08:11:37

In [14]:
df = df[df['updated_at'] >= df['created_at']]
df = df[df['end_date'] >= df['start_date']]

In [15]:
df

,event_id,user_id,event_name,event_description,event_type,location,event_image,start_date,end_date,created_at,updated_at
0,1,646,Persona Fest,A 24-hour coding hackathon solving real-world ...,cultural,Delhi,img3.png,2023-09-05 01:55:33,2023-09-06 01:55:33,2023-08-31 01:55:33,2023-09-20 01:55:33
1,2,582,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",placement,Delhi,img3.png,2023-08-31 11:46:03,2023-08-31 11:46:03,2023-08-30 11:46:03,2023-09-06 11:46:03
2,3,487,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Bangalore,img3.png,2024-07-20 10:45:21,2024-07-23 10:45:21,2024-07-15 10:45:21,2024-07-19 10:45:21
3,4,623,Aarohan,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Chennai,img2.png,2023-08-07 17:01:39,2023-08-09 17:01:39,2023-08-01 17:01:39,2023-08-31 17:01:39
4,5,118,MindSpark,The primary mission of the fest is to provide ...,hackathon,Mumbai,img1.png,2024-08-11 02:09:06,2024-08-14 02:09:06,2024-08-07 02:09:06,2024-08-19 02:09:06
...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,643,Hack-o-heist 2025,A 24-hour coding hackathon solving real-world ...,placement,Mumbai,img4.png,2024-10-13 23:40:56,2024-10-15 23:40:56,2024-10-12 23:40:56,2024-10-18 23:40:56
2496,2497,84,MindSpark,"Aarohan is divided into cultural, technical, m...",placement,Chennai,img3.png,2025-06-22 00:22:54,2025-06-22 00:22:54,2025-06-20 00:22:54,2025-07-20 00:22:54
2497,2498,109,Hack-o-heist 2025,The primary mission of the fest is to provide ...,technical,Delhi,img3.png,2023-08-30 12:26:52,2023-09-01 12:26:52,2023-08-27 12:26:52,2023-09-12 12:26:52
2498,2499,17,Campus Placement Drive,Campus placement drive with multiple recruiters.,hackathon,Mumbai,img4.png,2024-07-16 01:52:21,2024-07-16 01:52:21,2024-07-15 01:52:21,2024-07-30 01:52:21
2499,2500,830,MindSpark,Campus placement drive with multiple recruiters.,festival,Delhi,img3.png,2024-01-13 08:11:37,2024-01-15 08:11:37,2024-01-11 08:11:37,2024-01-20 08:11:37

In [16]:
df['event_type'] = df['event_type'].str.lower().str.strip()
df['event_name'] = df['event_name'].str.strip()
df['location'] = df['location'].str.strip()

In [17]:
df['event_type']

0        cultural
1       placement
2       technical
3       technical
4       hackathon
          ...
2495    placement
2496    placement
2497    technical
2498    hackathon
2499     festival
Name: event_type, Length: 2500, dtype: str

In [18]:
df

,event_id,user_id,event_name,event_description,event_type,location,event_image,start_date,end_date,created_at,updated_at
0,1,646,Persona Fest,A 24-hour coding hackathon solving real-world ...,cultural,Delhi,img3.png,2023-09-05 01:55:33,2023-09-06 01:55:33,2023-08-31 01:55:33,2023-09-20 01:55:33
1,2,582,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",placement,Delhi,img3.png,2023-08-31 11:46:03,2023-08-31 11:46:03,2023-08-30 11:46:03,2023-09-06 11:46:03
2,3,487,Campus Placement Drive,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Bangalore,img3.png,2024-07-20 10:45:21,2024-07-23 10:45:21,2024-07-15 10:45:21,2024-07-19 10:45:21
3,4,623,Aarohan,"The 19th edition, themed 'The Quantum Nexus', ...",technical,Chennai,img2.png,2023-08-07 17:01:39,2023-08-09 17:01:39,2023-08-01 17:01:39,2023-08-31 17:01:39
4,5,118,MindSpark,The primary mission of the fest is to provide ...,hackathon,Mumbai,img1.png,2024-08-11 02:09:06,2024-08-14 02:09:06,2024-08-07 02:09:06,2024-08-19 02:09:06
...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,643,Hack-o-heist 2025,A 24-hour coding hackathon solving real-world ...,placement,Mumbai,img4.png,2024-10-13 23:40:56,2024-10-15 23:40:56,2024-10-12 23:40:56,2024-10-18 23:40:56
2496,2497,84,MindSpark,"Aarohan is divided into cultural, technical, m...",placement,Chennai,img3.png,2025-06-22 00:22:54,2025-06-22 00:22:54,2025-06-20 00:22:54,2025-07-20 00:22:54
2497,2498,109,Hack-o-heist 2025,The primary mission of the fest is to provide ...,technical,Delhi,img3.png,2023-08-30 12:26:52,2023-09-01 12:26:52,2023-08-27 12:26:52,2023-09-12 12:26:52
2498,2499,17,Campus Placement Drive,Campus placement drive with multiple recruiters.,hackathon,Mumbai,img4.png,2024-07-16 01:52:21,2024-07-16 01:52:21,2024-07-15 01:52:21,2024-07-30 01:52:21
2499,2500,830,MindSpark,Campus placement drive with multiple recruiters.,festival,Delhi,img3.png,2024-01-13 08:11:37,2024-01-15 08:11:37,2024-01-11 08:11:37,2024-01-20 08:11:37

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   event_id           2500 non-null   int64
 1   user_id            2500 non-null   int64
 2   event_name         2500 non-null   str
 3   event_description  2500 non-null   str
 4   event_type         2500 non-null   str
 5   location           2500 non-null   str
 6   event_image        2500 non-null   str
 7   start_date         2500 non-null   datetime64[us]
 8   end_date           2500 non-null   datetime64[us]
 9   created_at         2500 non-null   datetime64[us]
 10  updated_at         2500 non-null   datetime64[us]
dtypes: datetime64[us](4), int64(2), str(5)
memory usage: 215.0 KB

In [20]:
#remove extra space and line bars
df['event_description'] = df['event_description'].str.strip()

In [21]:

df['event_description']

0       A 24-hour coding hackathon solving real-world ...
1       The 19th edition, themed 'The Quantum Nexus', ...
2       The 19th edition, themed 'The Quantum Nexus', ...
3       The 19th edition, themed 'The Quantum Nexus', ...
4       The primary mission of the fest is to provide ...
                              ...
2495    A 24-hour coding hackathon solving real-world ...
2496    Aarohan is divided into cultural, technical, m...
2497    The primary mission of the fest is to provide ...
2498     Campus placement drive with multiple recruiters.
2499     Campus placement drive with multiple recruiters.
Name: event_description, Length: 2500, dtype: str

In [22]:
#handles missing values
df['event_description'] = df['event_description'].fillna('not provided')

In [23]:
df['event_description']

0       A 24-hour coding hackathon solving real-world ...
1       The 19th edition, themed 'The Quantum Nexus', ...
2       The 19th edition, themed 'The Quantum Nexus', ...
3       The 19th edition, themed 'The Quantum Nexus', ...
4       The primary mission of the fest is to provide ...
                              ...
2495    A 24-hour coding hackathon solving real-world ...
2496    Aarohan is divided into cultural, technical, m...
2497    The primary mission of the fest is to provide ...
2498     Campus placement drive with multiple recruiters.
2499     Campus placement drive with multiple recruiters.
Name: event_description, Length: 2500, dtype: str

In [24]:
df['event_description'].duplicated().sum()

np.int64(2494)

In [25]:
df['event_description'].str.lower()

0       a 24-hour coding hackathon solving real-world ...
1       the 19th edition, themed 'the quantum nexus', ...
2       the 19th edition, themed 'the quantum nexus', ...
3       the 19th edition, themed 'the quantum nexus', ...
4       the primary mission of the fest is to provide ...
                              ...
2495    a 24-hour coding hackathon solving real-world ...
2496    aarohan is divided into cultural, technical, m...
2497    the primary mission of the fest is to provide ...
2498     campus placement drive with multiple recruiters.
2499     campus placement drive with multiple recruiters.
Name: event_description, Length: 2500, dtype: str

In [26]:
df.to_csv("events_cleaned.csv", index=False)