In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("comments.csv")

In [4]:
df

,comment_id,post_id,user_id,comment_text,created_at,updated_at
0,1,1411,338,"Very informative, thanks for sharing.",2024-01-23 00:00:00,2024-01-28 00:00:00
1,2,2537,434,"Very informative, thanks for sharing.",2024-02-06 00:00:00,2024-02-06 00:00:00
2,3,1729,358,Looking forward to more updates.,2024-12-27 00:00:00,2024-12-27 00:00:00
3,4,2050,117,"Very informative, thanks for sharing.",2024-01-16 00:00:00,2024-01-21 00:00:00
4,5,3615,379,Great post!,2024-08-26 00:00:00,2024-08-28 00:00:00
...,...,...,...,...,...,...
3995,3996,865,222,This is helpful.,2024-10-08 00:00:00,2024-10-13 00:00:00
3996,3997,2222,349,Great post!,2024-05-21 00:00:00,2024-05-25 00:00:00
3997,3998,1189,142,Nice explanation.,2024-09-13 00:00:00,2024-09-15 00:00:00
3998,3999,1797,288,Nice explanation.,2024-07-04 00:00:00,2024-07-09 00:00:00
3999,4000,845,461,Great post!,2024-05-27 00:00:00,2024-05-29 00:00:00

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   comment_id    4000 non-null   int64
 1   post_id       4000 non-null   int64
 2   user_id       4000 non-null   int64
 3   comment_text  4000 non-null   str
 4   created_at    4000 non-null   str
 5   updated_at    4000 non-null   str
dtypes: int64(3), str(3)
memory usage: 187.6 KB

In [6]:
df = df.drop_duplicates()

In [7]:
df

,comment_id,post_id,user_id,comment_text,created_at,updated_at
0,1,1411,338,"Very informative, thanks for sharing.",2024-01-23 00:00:00,2024-01-28 00:00:00
1,2,2537,434,"Very informative, thanks for sharing.",2024-02-06 00:00:00,2024-02-06 00:00:00
2,3,1729,358,Looking forward to more updates.,2024-12-27 00:00:00,2024-12-27 00:00:00
3,4,2050,117,"Very informative, thanks for sharing.",2024-01-16 00:00:00,2024-01-21 00:00:00
4,5,3615,379,Great post!,2024-08-26 00:00:00,2024-08-28 00:00:00
...,...,...,...,...,...,...
3995,3996,865,222,This is helpful.,2024-10-08 00:00:00,2024-10-13 00:00:00
3996,3997,2222,349,Great post!,2024-05-21 00:00:00,2024-05-25 00:00:00
3997,3998,1189,142,Nice explanation.,2024-09-13 00:00:00,2024-09-15 00:00:00
3998,3999,1797,288,Nice explanation.,2024-07-04 00:00:00,2024-07-09 00:00:00
3999,4000,845,461,Great post!,2024-05-27 00:00:00,2024-05-29 00:00:00

In [12]:
#Remove rows with empty comments
df = df.dropna(subset=["comment_text"])

In [13]:
df

,comment_id,post_id,user_id,comment_text,created_at,updated_at
0,1,1411,338,"Very informative, thanks for sharing.",2024-01-23 00:00:00,2024-01-28 00:00:00
1,2,2537,434,"Very informative, thanks for sharing.",2024-02-06 00:00:00,2024-02-06 00:00:00
2,3,1729,358,Looking forward to more updates.,2024-12-27 00:00:00,2024-12-27 00:00:00
3,4,2050,117,"Very informative, thanks for sharing.",2024-01-16 00:00:00,2024-01-21 00:00:00
4,5,3615,379,Great post!,2024-08-26 00:00:00,2024-08-28 00:00:00
...,...,...,...,...,...,...
3995,3996,865,222,This is helpful.,2024-10-08 00:00:00,2024-10-13 00:00:00
3996,3997,2222,349,Great post!,2024-05-21 00:00:00,2024-05-25 00:00:00
3997,3998,1189,142,Nice explanation.,2024-09-13 00:00:00,2024-09-15 00:00:00
3998,3999,1797,288,Nice explanation.,2024-07-04 00:00:00,2024-07-09 00:00:00
3999,4000,845,461,Great post!,2024-05-27 00:00:00,2024-05-29 00:00:00

In [14]:
#clean comment text

#1.convert to string
df["comment_text"] = df["comment_text"].astype(str)

In [15]:
df["comment_text"]

0       Very informative, thanks for sharing.
1       Very informative, thanks for sharing.
2            Looking forward to more updates.
3       Very informative, thanks for sharing.
4                                 Great post!
                        ...
3995                         This is helpful.
3996                              Great post!
3997                        Nice explanation.
3998                        Nice explanation.
3999                              Great post!
Name: comment_text, Length: 4000, dtype: str

In [16]:

# Remove leading & trailing spaces
df["comment_text"] = df["comment_text"].str.strip()

In [17]:
df["comment_text"]

0       Very informative, thanks for sharing.
1       Very informative, thanks for sharing.
2            Looking forward to more updates.
3       Very informative, thanks for sharing.
4                                 Great post!
                        ...
3995                         This is helpful.
3996                              Great post!
3997                        Nice explanation.
3998                        Nice explanation.
3999                              Great post!
Name: comment_text, Length: 4000, dtype: str

In [18]:
# Remove extra spaces inside text
df["comment_text"] = df["comment_text"].str.replace(r"\s+", " ", regex=True)

In [19]:
df["comment_text"]

0       Very informative, thanks for sharing.
1       Very informative, thanks for sharing.
2            Looking forward to more updates.
3       Very informative, thanks for sharing.
4                                 Great post!
                        ...
3995                         This is helpful.
3996                              Great post!
3997                        Nice explanation.
3998                        Nice explanation.
3999                              Great post!
Name: comment_text, Length: 4000, dtype: str

In [20]:

# Convert to lowercase (optional but recommended)
df["comment_text"] = df["comment_text"].str.lower()

In [21]:
df["comment_text"]

0       very informative, thanks for sharing.
1       very informative, thanks for sharing.
2            looking forward to more updates.
3       very informative, thanks for sharing.
4                                 great post!
                        ...
3995                         this is helpful.
3996                              great post!
3997                        nice explanation.
3998                        nice explanation.
3999                              great post!
Name: comment_text, Length: 4000, dtype: str

In [22]:
df = df[df["comment_text"] != ""]

In [23]:
df

,comment_id,post_id,user_id,comment_text,created_at,updated_at
0,1,1411,338,"very informative, thanks for sharing.",2024-01-23 00:00:00,2024-01-28 00:00:00
1,2,2537,434,"very informative, thanks for sharing.",2024-02-06 00:00:00,2024-02-06 00:00:00
2,3,1729,358,looking forward to more updates.,2024-12-27 00:00:00,2024-12-27 00:00:00
3,4,2050,117,"very informative, thanks for sharing.",2024-01-16 00:00:00,2024-01-21 00:00:00
4,5,3615,379,great post!,2024-08-26 00:00:00,2024-08-28 00:00:00
...,...,...,...,...,...,...
3995,3996,865,222,this is helpful.,2024-10-08 00:00:00,2024-10-13 00:00:00
3996,3997,2222,349,great post!,2024-05-21 00:00:00,2024-05-25 00:00:00
3997,3998,1189,142,nice explanation.,2024-09-13 00:00:00,2024-09-15 00:00:00
3998,3999,1797,288,nice explanation.,2024-07-04 00:00:00,2024-07-09 00:00:00
3999,4000,845,461,great post!,2024-05-27 00:00:00,2024-05-29 00:00:00

In [24]:
df["created_at"] = pd.to_datetime(df["created_at"], errors="coerce")

# ===============================
# STEP 3: Find rows with 00:00:00
# ===============================
mask = (
    (df["created_at"].dt.hour == 0) &
    (df["created_at"].dt.minute == 0) &
    (df["created_at"].dt.second == 0)
)

# ===============================
# STEP 4: Generate random time
# ===============================
random_hours = np.random.randint(1, 24, size=mask.sum())
random_minutes = np.random.randint(0, 60, size=mask.sum())
random_seconds = np.random.randint(0, 60, size=mask.sum())

# ===============================
# STEP 5: Replace time ONLY
# ===============================
df.loc[mask, "created_at"] = (
    df.loc[mask, "created_at"]
    + pd.to_timedelta(random_hours, unit="h")
    + pd.to_timedelta(random_minutes, unit="m")
    + pd.to_timedelta(random_seconds, unit="s")
)

# ===============================
# STEP 6: Save cleaned file
# ===============================
df.to_csv("comments_time_fixed.csv", index=False)

print("✅ 00:00:00 replaced with random HH:MM:SS and saved")

✅ 00:00:00 replaced with random HH:MM:SS and saved

In [25]:
df["created_at"]

0      2024-01-23 17:37:07
1      2024-02-06 06:33:25
2      2024-12-27 01:06:21
3      2024-01-16 01:23:18
4      2024-08-26 22:50:50
               ...
3995   2024-10-08 01:30:57
3996   2024-05-21 12:16:42
3997   2024-09-13 12:28:19
3998   2024-07-04 13:23:56
3999   2024-05-27 14:51:36
Name: created_at, Length: 4000, dtype: datetime64[us]

In [26]:
df["updated_at"] = pd.to_datetime(df["updated_at"], errors="coerce")

# ===============================
# STEP 3: Find rows with 00:00:00
# ===============================
mask = (
    (df["updated_at"].dt.hour == 0) &
    (df["updated_at"].dt.minute == 0) &
    (df["updated_at"].dt.second == 0)
)

# ===============================
# STEP 4: Generate random time
# ===============================
random_hours = np.random.randint(1, 24, size=mask.sum())
random_minutes = np.random.randint(0, 60, size=mask.sum())
random_seconds = np.random.randint(0, 60, size=mask.sum())

# ===============================
# STEP 5: Replace ONLY the time part
# ===============================
df.loc[mask, "updated_at"] = (
    df.loc[mask, "updated_at"]
    + pd.to_timedelta(random_hours, unit="h")
    + pd.to_timedelta(random_minutes, unit="m")
    + pd.to_timedelta(random_seconds, unit="s")
)

# ===============================
# STEP 6: Save cleaned file
# ===============================
df.to_csv("comments_updated_time_fixed.csv", index=False)

print("✅ updated_at time fixed and file saved")

✅ updated_at time fixed and file saved

In [27]:
df["updated_at"]

0      2024-01-28 13:48:49
1      2024-02-06 11:25:15
2      2024-12-27 10:58:38
3      2024-01-21 10:31:45
4      2024-08-28 12:14:13
               ...
3995   2024-10-13 04:23:35
3996   2024-05-25 05:32:20
3997   2024-09-15 20:15:29
3998   2024-07-09 04:42:48
3999   2024-05-29 23:21:41
Name: updated_at, Length: 4000, dtype: datetime64[us]

In [28]:
df

,comment_id,post_id,user_id,comment_text,created_at,updated_at
0,1,1411,338,"very informative, thanks for sharing.",2024-01-23 17:37:07,2024-01-28 13:48:49
1,2,2537,434,"very informative, thanks for sharing.",2024-02-06 06:33:25,2024-02-06 11:25:15
2,3,1729,358,looking forward to more updates.,2024-12-27 01:06:21,2024-12-27 10:58:38
3,4,2050,117,"very informative, thanks for sharing.",2024-01-16 01:23:18,2024-01-21 10:31:45
4,5,3615,379,great post!,2024-08-26 22:50:50,2024-08-28 12:14:13
...,...,...,...,...,...,...
3995,3996,865,222,this is helpful.,2024-10-08 01:30:57,2024-10-13 04:23:35
3996,3997,2222,349,great post!,2024-05-21 12:16:42,2024-05-25 05:32:20
3997,3998,1189,142,nice explanation.,2024-09-13 12:28:19,2024-09-15 20:15:29
3998,3999,1797,288,nice explanation.,2024-07-04 13:23:56,2024-07-09 04:42:48
3999,4000,845,461,great post!,2024-05-27 14:51:36,2024-05-29 23:21:41

In [29]:
df.to_csv("comments_time_fixed.csv", index=False)