In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("USER.csv")   # or pd.read_excel("file.xlsx")

In [3]:
df

,user_id,college_id,name,email,phone_number,college_name,signup_date,updated_at,status
0,1,158,Sneha Singh,sneha1@gmail.com,9967414785,ABC College,18-01-2023,03-02-2023,Inactive
1,2,153,Amit Verma,amit2@gmail.com,9632341726,XYZ College,04-04-2024,16-05-2024,Inactive
2,3,113,Priya Khan,priya3@gmail.com,9564566906,ABC College,28-03-2024,27-05-2024,Inactive
3,4,189,Amit Gupta,amit4@gmail.com,9658340847,PQR Institute,23-12-2024,15-02-2025,Active
4,5,200,Anjali Khan,anjali5@gmail.com,9533732985,PQR Institute,17-05-2024,20-05-2024,Active
...,...,...,...,...,...,...,...,...,...
995,996,174,Rohan Singh,rohan996@gmail.com,9480675229,ABC College,12-10-2023,20-11-2023,Active
996,997,181,Rohan Khan,rohan997@gmail.com,9246052039,XYZ College,14-07-2024,29-07-2024,Inactive
997,998,175,Amit Verma,amit998@gmail.com,9376598855,LMN University,20-11-2023,05-01-2024,Active
998,999,180,Amit Gupta,amit999@gmail.com,9790885365,LMN University,29-03-2024,19-05-2024,Active
999,1000,119,Rahul Verma,rahul1000@gmail.com,9834231140,ABC College,23-05-2024,12-06-2024,Inactive

In [4]:
duplicate_count = df.duplicated().sum()
df = df.drop_duplicates()

In [5]:
df

,user_id,college_id,name,email,phone_number,college_name,signup_date,updated_at,status
0,1,158,Sneha Singh,sneha1@gmail.com,9967414785,ABC College,18-01-2023,03-02-2023,Inactive
1,2,153,Amit Verma,amit2@gmail.com,9632341726,XYZ College,04-04-2024,16-05-2024,Inactive
2,3,113,Priya Khan,priya3@gmail.com,9564566906,ABC College,28-03-2024,27-05-2024,Inactive
3,4,189,Amit Gupta,amit4@gmail.com,9658340847,PQR Institute,23-12-2024,15-02-2025,Active
4,5,200,Anjali Khan,anjali5@gmail.com,9533732985,PQR Institute,17-05-2024,20-05-2024,Active
...,...,...,...,...,...,...,...,...,...
995,996,174,Rohan Singh,rohan996@gmail.com,9480675229,ABC College,12-10-2023,20-11-2023,Active
996,997,181,Rohan Khan,rohan997@gmail.com,9246052039,XYZ College,14-07-2024,29-07-2024,Inactive
997,998,175,Amit Verma,amit998@gmail.com,9376598855,LMN University,20-11-2023,05-01-2024,Active
998,999,180,Amit Gupta,amit999@gmail.com,9790885365,LMN University,29-03-2024,19-05-2024,Active
999,1000,119,Rahul Verma,rahul1000@gmail.com,9834231140,ABC College,23-05-2024,12-06-2024,Inactive

In [6]:
missing_values = df.isnull().sum()

In [7]:
missing_percent = (df.isnull().sum() / len(df)) * 100

In [8]:
missing_percent

user_id         0.0
college_id      0.0
name            0.0
email           0.0
phone_number    0.0
college_name    0.0
signup_date     0.0
updated_at      0.0
status          0.0
dtype: float64

In [9]:
df = df.fillna("Unknown")  # Example
# OR
df = df.dropna()

In [10]:
df

,user_id,college_id,name,email,phone_number,college_name,signup_date,updated_at,status
0,1,158,Sneha Singh,sneha1@gmail.com,9967414785,ABC College,18-01-2023,03-02-2023,Inactive
1,2,153,Amit Verma,amit2@gmail.com,9632341726,XYZ College,04-04-2024,16-05-2024,Inactive
2,3,113,Priya Khan,priya3@gmail.com,9564566906,ABC College,28-03-2024,27-05-2024,Inactive
3,4,189,Amit Gupta,amit4@gmail.com,9658340847,PQR Institute,23-12-2024,15-02-2025,Active
4,5,200,Anjali Khan,anjali5@gmail.com,9533732985,PQR Institute,17-05-2024,20-05-2024,Active
...,...,...,...,...,...,...,...,...,...
995,996,174,Rohan Singh,rohan996@gmail.com,9480675229,ABC College,12-10-2023,20-11-2023,Active
996,997,181,Rohan Khan,rohan997@gmail.com,9246052039,XYZ College,14-07-2024,29-07-2024,Inactive
997,998,175,Amit Verma,amit998@gmail.com,9376598855,LMN University,20-11-2023,05-01-2024,Active
998,999,180,Amit Gupta,amit999@gmail.com,9790885365,LMN University,29-03-2024,19-05-2024,Active
999,1000,119,Rahul Verma,rahul1000@gmail.com,9834231140,ABC College,23-05-2024,12-06-2024,Inactive

In [12]:
df['signup_date'] = pd.to_datetime(df['signup_date'], errors='coerce')

C:\Users\Prajakta\AppData\Local\Temp\ipykernel_17240\4099826991.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['signup_date'] = pd.to_datetime(df['signup_date'], errors='coerce')

In [13]:
df['signup_date']

0     2023-01-18
1     2024-04-04
2     2024-03-28
3     2024-12-23
4     2024-05-17
         ...
995   2023-10-12
996   2024-07-14
997   2023-11-20
998   2024-03-29
999   2024-05-23
Name: signup_date, Length: 1000, dtype: datetime64[us]

In [15]:
invalid_dates = df['signup_date'].isnull().sum()

In [16]:
invalid_dates

np.int64(0)

In [17]:
numeric_cols = df.select_dtypes(include=np.number).columns

outlier_counts = {}

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    outlier_counts[col] = len(outliers)

In [18]:
numeric_cols

Index(['user_id', 'college_id', 'phone_number'], dtype='str')

In [23]:
df['name'] = df['name'].str.strip().str.title()

In [24]:
df['name']

0      Sneha Singh
1       Amit Verma
2       Priya Khan
3       Amit Gupta
4      Anjali Khan
          ...
995    Rohan Singh
996     Rohan Khan
997     Amit Verma
998     Amit Gupta
999    Rahul Verma
Name: name, Length: 1000, dtype: str

In [25]:
invalid_name = df[df['name'].str.contains(r'[^a-zA-Z ]', regex=True)]

In [26]:
invalid_name

Empty DataFrame
Columns: [user_id, college_id, name, email, phone_number, college_name, signup_date, updated_at, status]
Index: []

In [27]:
df['email'] = df['email'].str.strip().str.lower()

In [28]:
df['email']

0         sneha1@gmail.com
1          amit2@gmail.com
2         priya3@gmail.com
3          amit4@gmail.com
4        anjali5@gmail.com
              ...
995     rohan996@gmail.com
996     rohan997@gmail.com
997      amit998@gmail.com
998      amit999@gmail.com
999    rahul1000@gmail.com
Name: email, Length: 1000, dtype: str

In [29]:
email_pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'
invalid_email = df[~df['email'].str.match(email_pattern)]

In [30]:
df['phone_number'] = df['phone_number'].astype(str)
df['phone_number'] = df['phone_number'].str.replace(r'\D', '', regex=True)

phone_pattern = r'^[6-9]\d{9}$'
invalid_phone = df[~df['phone_number'].str.match(phone_pattern)]

In [31]:
df['college_name'] = df['college_name'].str.strip().str.title()

In [32]:
df['college_name'].unique()

<StringArray>
['Abc College', 'Xyz College', 'Pqr Institute', 'Lmn University']
Length: 4, dtype: str

In [33]:
df['signup_date'] = pd.to_datetime(df['signup_date'], format='%d-%m-%Y', errors='coerce')
df['updated_at'] = pd.to_datetime(df['updated_at'], format='%d-%m-%Y', errors='coerce')

In [34]:
invalid_dates = df[df['updated_at'] < df['signup_date']]

In [35]:
df['status'] = df['status'].str.strip().str.title()

df['status'] = df['status'].replace({
    'Inactiv': 'Inactive'
})

In [37]:

df['user_id'].duplicated().sum()

np.int64(0)

In [48]:
df.to_csv("cleaned_USER_data.csv", index=False)

In [41]:
report = pd.DataFrame({
    "Column_Name": df.columns,
    "Data_Type": df.dtypes.values,
    
    "Missing_Count": df.isnull().sum().values,
    
    "Duplicate_Count": [df[col].duplicated().sum() for col in df.columns],
    "Unique_Values": df.nunique().values
})

In [44]:
report["Invalid_Email_Count"] = report["Column_Name"].apply(
    lambda x: len(invalid_email) if x == "email" else 0
)

report["Invalid_Phone_Count"] = report["Column_Name"].apply(
    lambda x: len(invalid_phone) if x == "phone_number" else 0
)

In [45]:
report.to_csv("data_quality_report.csv", index=False)